import type { Bracket, Team, Tournament } from "@/lib/types";

export const demoTournament: Tournament = {
  id: "demo-tournament",
  name: "Americano Open 2026",
  location: "Buenos Aires Lawn Club",
  startDate: "2026-08-14",
  signupOpen: true,
  bracketsPublished: true,
  description:
    "A weekend Americano-style tennis event with curated team brackets, live updates, and a duo-first mobile experience.",
};

export const demoTeams: Team[] = [
  {
    id: "admin-1",
    slug: "direccion-torneo",
    playerOneName: "Lucas",
    playerTwoName: "Admin",
    teamName: "Lucas & Admin",
    email: "lucas@americanoopen.com",
    phone: "+54 11 5555-0001",
    role: "admin",
    approvalStatus: "approved",
    category: "Tournament Director",
    bio: "Oversees check-in, approvals, and bracket publishing.",
    avatarUrl: null,
  },
  {
    id: "team-1",
    slug: "sofia-mateo",
    playerOneName: "Sofia Rojas",
    playerTwoName: "Mateo Acosta",
    teamName: "Sofia Rojas & Mateo Acosta",
    email: "sofia.mateo@example.com",
    phone: "+54 11 5555-0002",
    role: "client",
    approvalStatus: "approved",
    category: "Intermediate",
    bio: "Balanced duo with heavy topspin from the baseline and fast hands at the net.",
    avatarUrl: null,
  },
  {
    id: "team-2",
    slug: "clara-julieta",
    playerOneName: "Clara Benitez",
    playerTwoName: "Julieta Pardo",
    teamName: "Clara Benitez & Julieta Pardo",
    email: "clara.julieta@example.com",
    phone: "+54 11 5555-0003",
    role: "client",
    approvalStatus: "approved",
    category: "Advanced",
    bio: "Big serving pair that likes to close points early and stay aggressive.",
    avatarUrl: null,
  },
  {
    id: "team-3",
    slug: "paula-lara",
    playerOneName: "Paula Diaz",
    playerTwoName: "Lara Quiroga",
    teamName: "Paula Diaz & Lara Quiroga",
    email: "paula.lara@example.com",
    phone: "+54 11 5555-0004",
    role: "client",
    approvalStatus: "pending",
    category: "Beginner",
    bio: "First tournament together and still waiting for approval.",
    avatarUrl: null,
  },
];

export const demoBrackets: Bracket[] = [
  {
    id: "bracket-1",
    tournamentId: demoTournament.id,
    name: "Saturday Sunrise Draw",
    format: "Americano - 4 teams",
    status: "published",
    publishedAt: "2026-08-10T14:00:00.000Z",
    entries: [demoTeams[1], demoTeams[2]].map((team, index) => ({
      id: `entry-${index + 1}`,
      bracketId: "bracket-1",
      teamId: team.id,
      position: index + 1,
      seed: index + 1,
      team: {
        id: team.id,
        slug: team.slug,
        playerOneName: team.playerOneName,
        playerTwoName: team.playerTwoName,
        teamName: team.teamName,
        avatarUrl: team.avatarUrl,
        category: team.category,
        approvalStatus: team.approvalStatus,
        bio: team.bio,
      },
    })),
  },
];
